name: Create Manual Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Имя тега (например, v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_title:
        description: 'Заголовок релиза (Title)'
        required: true
        default: 'Релиз v1.0.0'
      release_body:
        description: 'Описание релиза (Чейнджлог)'
        required: false
        default: 'Ручной релиз собранных файлов.'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Нужно для создания релиза и загрузки файлов

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Скачиваем ВСЕ артефакты из последней успешной сборки, имя которых начинается на build-output-
      - name: Download all artifacts from Build workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
          name: build-output-* # Находит build-output-2017, build-output-2018 и т.д.
          path: ./artifacts   # Скачивает их все в одну общую папку
          name_is_regexp: true # Включает поддержку поиска по маске *

      # 2. Создаем релиз и прикрепляем все найденные внутри папки APK-файлы
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_title }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false
          files: ./artifacts/**/*
