name: Create Manual Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Имя тега (например, v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_title:
        description: 'Заголовок релиза (Title)'
        required: true
        default: 'Релиз v1.0.0'
      generate_notes:
        description: 'Сгенерировать описание автоматически? (Галочка)'
        type: boolean
        required: false
        default: true
      release_body:
        description: 'Собственное описание (если галочка выключена)'
        required: false
        default: 'Ручной релиз собранных файлов.'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Нужно для создания релиза и загрузки файлов

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Скачиваем ВСЕ APK из последней успешной сборки build.yml
      # Благодаря маске build-output-* скрипт заберет файлы всех версий из матрицы
      - name: Download all artifacts from Build workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
          name: build-output-*
          path: ./artifacts
          name_is_regexp: true

      # 2. Создаем GitHub Релиз и прикрепляем скачанные файлы
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_title }}
          # Если галочка generate_notes активна, встроенная генерация GitHub перекроет это поле своим списком коммитов
          body: ${{ github.event.inputs.generate_notes == 'true' && '' || github.event.inputs.release_body }}
          generate_release_notes: ${{ github.event.inputs.generate_notes }}
          draft: false
          prerelease: false
          files: ./artifacts/**/*
